/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.ds;

public class Test {
 
	static public void main(String str[]) {
	
		System.out.println("<-- Begin Executing --->");
    
		start();
	}

	private static void start() {
		sample.ds.tree.Tree.builder().start();
	}
}
